# 变量
variables:
  REGISTRY_DOMAIN: "harbor.jiguang.dev"
  REGISTRY_NAMESPACE: "pos_dine_api"

# 缓存
cache:
  paths:
    - pkg/mod/

# 阶段
stages:
  - build
  - migrate
  - deploy

# 引入
include:
  - local: .gitlab/*.gitlab-ci.yml

before_script:
  - echo "开始构建，当前分支为：$CI_COMMIT_REF_SLUG，当前运行目录为：" $(pwd)
