[BUSINESS_TYPE_noodle]
other = "Noodle shop"

[BUSINESS_TYPE_bakery]
other = "Bakery & desserts"

[BUSINESS_TYPE_snack]
other = "Snack"

[BUSINESS_TYPE_drink]
other = "Beverage"

[BUSINESS_TYPE_chinese_food]
other = "Chinese food"