[Database]
AutoMigrate = false
Debug = true
Host = "127.0.0.1"
Port = "33061"
User = "root"
Password = "pass"
Name = "dine"
TimeZone = "Asia/Shanghai"
MaxLifetime = 3600
MaxOpenConns = 150
MaxIdleConns = 50

[Alert]
AppName = "scheduler"
AccessToken = "access_token"
Secret = "secret"
Ats = ["123456", "7891011"]

[Redis]
Addr = "127.0.0.1:6379"
Username = ""
Password = "123456"
DB = 0

[Huifu]
ProductId = "product_id"
SysId = "sys_id"
RsaMerchPrivateKey = "rsa_merch_private_key"
RsaHuifuPublicKey = "rsa_huifu_public_key"

[Oss]
Region = "cn-shanghai"
Bucket = "bucket"
Dir = "dine"
AccessKeyID = "access_key_id"
AccessKeySecret = "access_key_secret"
RoleARN = "role_arn"
SessionName = "dine-scheduler"
Expiration = 3600

# 分账账单生成时间：每天凌晨2点
[ProfitDistribution]
Cron = "@every 10s"
# Cron = "5 0 * * *"